[tool.black]
line-length = 79
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | env
  | venv
  | .eggs
)/
'''

[tool.mypy]
disable_error_code = ["import-untyped", "attr-defined"]
