common:
  orderly_endpoint: https://api-evm.orderly.network
  statistical_days: 30
rate:
  fee_tier:
    - maker_fee: 0.03%
      taker_fee: 0.06%
      tier: "1"
      volume_max: 500000
      volume_min: 0
    - maker_fee: 0.02%
      taker_fee: 0.05%
      tier: "2"
      volume_max: 2500000
      volume_min: 500000
    - maker_fee: 0.015%
      taker_fee: 0.045%
      tier: "3"
      volume_max: 10000000
      volume_min: 2500000
    - maker_fee: 0.01%
      taker_fee: 0.04%
      tier: "4"
      volume_max: 50000000
      volume_min: 10000000
    - maker_fee: 0.005%
      taker_fee: 0.035%
      tier: "5"
      volume_max: 125000000
      volume_min: 50000000
    - maker_fee: 0%
      taker_fee: 0.03%
      tier: "6"
      volume_max: null
      volume_min: 125000000
  special_rate_whitelists:
    - "0x"
  startup_batch_update_fee: true
